language: node_js
node_js:
  - "10"
services:
  - mongodb
cache:
  yarn: true
install:
  - yarn
script:
  - yarn workspace api build
  - yarn workspace api test --verbose
  - yarn workspace client typecheck
  - yarn workspace client build
  - yarn workspace client test
# before_deploy: yarn global add now
# deploy:
#   - provider: script # Run a custom deployment script which we will define below
#     script: now alias --token $NOW_TOKEN
#     skip_cleanup: true
#     on:
#       all_branches: true
#       master: false
